In [19]:
import pandas as pd

In [20]:
weather01 = pd.read_csv('IndianWeatherRepository 1.csv')
weather01.head()

,country,location_name,region,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,India,Ashoknagar,Madhya Pradesh,24.57,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,12.6,18.5,1,2,05:59 AM,06:41 PM,05:42 PM,03:38 AM,Waxing Gibbous,93
1,India,Raisen,Madhya Pradesh,23.33,77.80,Asia/Kolkata,1693286100,2023-08-29 10:45,27.5,81.5,...,10.7,14.2,1,1,06:00 AM,06:40 PM,05:39 PM,03:41 AM,Waxing Gibbous,93
2,India,Chhindwara,Madhya Pradesh,22.07,78.93,Asia/Kolkata,1693286100,2023-08-29 10:45,26.3,79.3,...,16.8,20.7,2,2,05:56 AM,06:34 PM,05:32 PM,03:39 AM,Waxing Gibbous,93
3,India,Betul,Madhya Pradesh,21.86,77.93,Asia/Kolkata,1693286100,2023-08-29 10:45,25.6,78.1,...,4.9,6.6,1,1,06:00 AM,06:38 PM,05:36 PM,03:43 AM,Waxing Gibbous,93
4,India,Hoshangabad,Madhya Pradesh,22.75,77.72,Asia/Kolkata,1693286100,2023-08-29 10:45,27.2,81.0,...,11.4,14.8,1,1,06:01 AM,06:39 PM,05:38 PM,03:42 AM,Waxing Gibbous,93

In [21]:
columns_to_drop =['country','timezone','last_updated_epoch','sunrise','sunset','moonrise','moonset','moon_phase','moon_illumination','wind_mph','wind_degree','wind_direction','pressure_mb','precip_in','feels_like_celsius','feels_like_fahrenheit','visibility_miles','uv_index','gust_mph','gust_kph','temperature_fahrenheit']
weather01 = weather01.drop(columns_to_drop, axis=1)
weather01.head()

,location_name,region,latitude,longitude,last_updated,temperature_celsius,condition_text,wind_kph,pressure_in,precip_mm,...,cloud,visibility_km,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index
0,Ashoknagar,Madhya Pradesh,24.57,77.72,2023-08-29 10:45,27.5,Partly cloudy,20.5,29.77,0.0,...,26,10.0,243.7,45.8,1.7,3.1,12.6,18.5,1,2
1,Raisen,Madhya Pradesh,23.33,77.80,2023-08-29 10:45,27.5,Sunny,15.5,29.78,0.0,...,19,10.0,240.3,38.3,2.1,2.6,10.7,14.2,1,1
2,Chhindwara,Madhya Pradesh,22.07,78.93,2023-08-29 10:45,26.3,Partly cloudy,18.4,29.78,0.0,...,51,10.0,220.3,57.2,0.6,1.7,16.8,20.7,2,2
3,Betul,Madhya Pradesh,21.86,77.93,2023-08-29 10:45,25.6,Cloudy,16.9,29.80,0.0,...,65,10.0,200.3,25.0,1.2,1.1,4.9,6.6,1,1
4,Hoshangabad,Madhya Pradesh,22.75,77.72,2023-08-29 10:45,27.2,Cloudy,16.2,29.79,0.0,...,82,10.0,257.0,30.8,2.2,1.8,11.4,14.8,1,1

In [22]:
first_row = weather01.iloc[0]
print(first_row)

location_name                         Ashoknagar
region                            Madhya Pradesh
latitude                                   24.57
longitude                                  77.72
last_updated                    2023-08-29 10:45
temperature_celsius                         27.5
condition_text                     Partly cloudy
wind_kph                                    20.5
pressure_in                                29.77
precip_mm                                    0.0
humidity                                      67
cloud                                         26
visibility_km                               10.0
air_quality_Carbon_Monoxide                243.7
air_quality_Ozone                           45.8
air_quality_Nitrogen_dioxide                 1.7
air_quality_Sulphur_dioxide                  3.1
air_quality_PM2.5                           12.6
air_quality_PM10                            18.5
air_quality_us-epa-index                       1
air_quality_gb-defra-index                     2
Name: 0, dtype: object

In [23]:
#renaming our columns
weather01 = weather01.rename(columns={'location_name':'location','last_updated':'date','condition_text':'cloud_cover'})
weather01.head()

,location,region,latitude,longitude,date,temperature_celsius,cloud_cover,wind_kph,pressure_in,precip_mm,...,cloud,visibility_km,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index
0,Ashoknagar,Madhya Pradesh,24.57,77.72,2023-08-29 10:45,27.5,Partly cloudy,20.5,29.77,0.0,...,26,10.0,243.7,45.8,1.7,3.1,12.6,18.5,1,2
1,Raisen,Madhya Pradesh,23.33,77.80,2023-08-29 10:45,27.5,Sunny,15.5,29.78,0.0,...,19,10.0,240.3,38.3,2.1,2.6,10.7,14.2,1,1
2,Chhindwara,Madhya Pradesh,22.07,78.93,2023-08-29 10:45,26.3,Partly cloudy,18.4,29.78,0.0,...,51,10.0,220.3,57.2,0.6,1.7,16.8,20.7,2,2
3,Betul,Madhya Pradesh,21.86,77.93,2023-08-29 10:45,25.6,Cloudy,16.9,29.80,0.0,...,65,10.0,200.3,25.0,1.2,1.1,4.9,6.6,1,1
4,Hoshangabad,Madhya Pradesh,22.75,77.72,2023-08-29 10:45,27.2,Cloudy,16.2,29.79,0.0,...,82,10.0,257.0,30.8,2.2,1.8,11.4,14.8,1,1

In [24]:
# Converting 'date' column to datetime format
weather01['date_time'] = pd.to_datetime(weather01['date'], format='%Y-%m-%d %H:%M')
weather01.head()

,location,region,latitude,longitude,date,temperature_celsius,cloud_cover,wind_kph,pressure_in,precip_mm,...,visibility_km,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,date_time
0,Ashoknagar,Madhya Pradesh,24.57,77.72,2023-08-29 10:45,27.5,Partly cloudy,20.5,29.77,0.0,...,10.0,243.7,45.8,1.7,3.1,12.6,18.5,1,2,2023-08-29 10:45:00
1,Raisen,Madhya Pradesh,23.33,77.80,2023-08-29 10:45,27.5,Sunny,15.5,29.78,0.0,...,10.0,240.3,38.3,2.1,2.6,10.7,14.2,1,1,2023-08-29 10:45:00
2,Chhindwara,Madhya Pradesh,22.07,78.93,2023-08-29 10:45,26.3,Partly cloudy,18.4,29.78,0.0,...,10.0,220.3,57.2,0.6,1.7,16.8,20.7,2,2,2023-08-29 10:45:00
3,Betul,Madhya Pradesh,21.86,77.93,2023-08-29 10:45,25.6,Cloudy,16.9,29.80,0.0,...,10.0,200.3,25.0,1.2,1.1,4.9,6.6,1,1,2023-08-29 10:45:00
4,Hoshangabad,Madhya Pradesh,22.75,77.72,2023-08-29 10:45,27.2,Cloudy,16.2,29.79,0.0,...,10.0,257.0,30.8,2.2,1.8,11.4,14.8,1,1,2023-08-29 10:45:00

In [25]:
#Now we will calculate Temporal aggregation which we will use further 
# Calculate daily average temperature, humidity, and total precipitation
daily_aggregated_data = weather01.resample('D', on='date_time').agg({
    'temperature_celsius': 'mean',
    'humidity': 'mean',
    'precip_mm': 'sum'
})

print("Daily Aggregated Data:")
print(daily_aggregated_data.head())

Daily Aggregated Data:
            temperature_celsius   humidity  precip_mm
date_time
2023-08-29            29.666667  59.926335       27.1
2023-08-30            28.246909  65.676364       26.2
2023-08-31            24.940182  76.690909      122.4
2023-09-01            25.379779  76.154412      206.0
2023-09-02            25.628780  75.327869      268.4

In [26]:
#Grouping differet locations for further actions
grouped_data = weather01.groupby(['location'])
#you can repeat this function with different locations
Ashoknagar = grouped_data.get_group('Ashoknagar')
Ashoknagar.head()

,location,region,latitude,longitude,date,temperature_celsius,cloud_cover,wind_kph,pressure_in,precip_mm,...,visibility_km,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,date_time
0,Ashoknagar,Madhya Pradesh,24.57,77.72,2023-08-29 10:45,27.5,Partly cloudy,20.5,29.77,0.0,...,10.0,243.7,45.8,1.7,3.1,12.6,18.5,1,2,2023-08-29 10:45:00
543,Ashoknagar,Madhya Pradesh,24.57,77.72,2023-08-30 08:45,25.6,Sunny,18.0,29.81,0.0,...,10.0,243.7,46.5,1.8,3.5,24.9,32.3,2,3,2023-08-30 08:45:00
1093,Ashoknagar,Madhya Pradesh,24.57,77.72,2023-08-31 05:15,23.6,Partly cloudy,15.1,29.76,0.0,...,10.0,257.0,33.6,2.0,0.5,19.9,28.1,2,2,2023-08-31 05:15:00
1643,Ashoknagar,Madhya Pradesh,24.57,77.72,2023-09-01 05:15,24.2,Clear,13.3,29.76,0.0,...,10.0,270.4,48.6,1.8,1.4,38.3,52.7,2,4,2023-09-01 05:15:00
2187,Ashoknagar,Madhya Pradesh,24.57,77.72,2023-09-02 05:15,24.9,Clear,12.6,29.74,0.0,...,10.0,277.0,60.1,1.7,2.4,42.3,55.0,3,5,2023-09-02 05:15:00

In [27]:
# Now we will perform 'Moving Averages' for short term fluctuation in the dataset
# Calculate 7-day moving average of temperature
weather01['temperature_7day_ma'] = weather01['temperature_celsius'].rolling(window=7).mean()
weather01['humidity_7day_ma'] = weather01['humidity'].rolling(window=7).mean()
weather01['wind_speed_7day_ma'] = weather01['wind_kph'].rolling(window=7).mean()
print("weather01 Data with Moving Averages:")
print(weather01[['date', 'temperature_celsius', 'temperature_7day_ma','humidity','humidity_7day_ma','wind_kph','wind_speed_7day_ma']])
#Remember these are new columns in our dataset

weather01 Data with Moving Averages:
                    date  temperature_celsius  temperature_7day_ma  humidity  \
0       2023-08-29 10:45                 27.5                  NaN        67
1       2023-08-29 10:45                 27.5                  NaN        70
2       2023-08-29 10:45                 26.3                  NaN        70
3       2023-08-29 10:45                 25.6                  NaN        76
4       2023-08-29 10:45                 27.2                  NaN        74
...                  ...                  ...                  ...       ...
109531  2024-03-19 22:00                 25.0            25.942857        39
109532  2024-03-19 22:00                 20.6            25.314286        34
109533  2024-03-19 22:00                 23.8            25.142857        72
109534  2024-03-19 22:00                 30.0            25.571429        62
109535  2024-03-19 22:00                 24.2            25.457143        13

        humidity_7day_ma  wind_kph  wind_speed_7day_ma
0                    NaN      20.5                 NaN
1                    NaN      15.5                 NaN
2                    NaN      18.4                 NaN
3                    NaN      16.9                 NaN
4                    NaN      16.2                 NaN
...                  ...       ...                 ...
109531         51.714286       6.1            8.128571
109532         51.000000       3.6            7.771429
109533         50.285714      11.5            8.900000
109534         48.571429       9.0            8.585714
109535         44.857143       3.6            8.228571

[109536 rows x 7 columns]

In [34]:
import pandas as pd
#'weather' is variable for our dataset
weather = pd.read_csv('historic_weather_data.csv')
weather

,Date,Time,Temperature (C),Humidity,Wind Speed (km/h),Precipitation (mm)
0,2024-03-01,00:00,1.8,36,11.2,0.00
1,2024-03-01,01:00,1.4,37,11.2,0.00
2,2024-03-01,02:00,1.2,37,9.7,0.00
3,2024-03-01,03:00,1.1,37,8.3,0.00
4,2024-03-01,04:00,0.9,37,8.3,0.00
...,...,...,...,...,...,...
763,2024-04-01,19:00,7.7,85,12.2,0.01
764,2024-04-01,20:00,7.6,84,10.4,0.01
765,2024-04-01,21:00,7.4,84,8.6,0.01
766,2024-04-01,22:00,7.4,84,8.6,0.00
767,2024-04-01,23:00,7.3,84,8.3,0.00

In [32]:
#renaming our columns
weather = weather.rename(columns={'Temperature (C)':'temperature'})
weather = weather.rename(columns={'Precipitation (mm)':'precipitation'})
weather = weather.rename(columns={'Wind Speed (km/h)':'wind_speed'})
weather = weather.rename(columns={'Humidity':'humidity'})
weather.head()

         Date   Time  temperature  humidity  wind_speed  precipitation
0  2024-03-01  00:00          1.8        36        11.2            0.0
1  2024-03-01  01:00          1.4        37        11.2            0.0
2  2024-03-01  02:00          1.2        37         9.7            0.0
3  2024-03-01  03:00          1.1        37         8.3            0.0
4  2024-03-01  04:00          0.9        37         8.3            0.0

In [39]:
# Convert 'date','time' column to datetime format
weather['date'] = pd.to_datetime(weather['Date'], format="%Y-%m-%d")
weather['time'] = pd.to_datetime(weather['Time'], format='%H:%M')

In [ ]:
#Now we will calculate the mean , varience and standard deviation for further applying
# with columns 'temperature', 'humidity','precipitation' and 'wind_speed'

# Calculate mean, variance, and standard deviation of temperature
temperature_mean = weather['temperature'].mean()
temperature_variance = weather['temperature'].var()
temperature_std = weather['temperature'].std()

# Calculate mean, variance, and standard deviation of humidity
humidity_mean = weather['humidity'].mean()
humidity_variance = weather['humidity'].var()
humidity_std = weather['humidity'].std()

# Calculate mean, variance, and standard deviation of wind speed
wind_speed_mean = weather['wind_speed'].mean()
wind_speed_variance = weather['wind_speed'].var()
wind_speed_std = weather['wind_speed'].std()

# Calculate mean, variance, and standard deviation of temperature
precipitation_mean = weather['precipitation'].mean()
precipitation_variance = weather['precipitation'].var()
precipitation_std = weather['precipitation'].std()

print("Temperature - Mean: {}, Variance: {}, Standard Deviation: {}".format(temperature_mean, temperature_variance, temperature_std))
print("Humidity - Mean: {}, Variance: {}, Standard Deviation: {}".format(humidity_mean, humidity_variance, humidity_std))
print("Wind Speed - Mean: {}, Variance: {}, Standard Deviation: {}".format(wind_speed_mean, wind_speed_variance, wind_speed_std))
print("Precipitation - Mean: {}, variance: {}, Standard Deviation: {}".format(precipitation_mean, precipitation_variance, precipitation_std))

Temperature - Mean: 11.005357142857143, Variance: 18.519192686056456, Standard Deviation: 4.303393159595862
Humidity - Mean: 53.55357142857143, Variance: 194.20070573139435, Standard Deviation: 13.93559133052467
Wind Speed - Mean: 15.41547619047619, Variance: 43.82945965212432, Standard Deviation: 6.620382137922578
Precipitation - Mean: 0.025357142857142856, variance: 0.018445380667236957, Standard Deviation: 0.1358137720087214

In [ ]:
#Now we will calculate Temporal aggregation which we will use further 
# Calculate daily average temperature, humidity, and total precipitation
daily_aggregated_data = weather.resample('D', on='date').agg({
    'temperature': 'mean',
    'humidity': 'mean',
    'precipitation': 'sum'
})

print("Daily Aggregated Data:")
print(daily_aggregated_data.head())

Daily Aggregated Data:
            temperature   humidity  precipitation
date
2024-03-13    13.191667  58.208333           0.00
2024-03-14    14.683333  62.083333           0.00
2024-03-15    15.366667  68.208333           4.25
2024-03-16     9.937500  52.333333           0.00
2024-03-17    11.850000  48.625000           0.00

In [ ]:
# Now we will perform 'Moving Averages' for short term fluctuation in the dataset
# Calculate 7-day moving average of temperature
weather['temperature_7day_ma'] = weather['temperature'].rolling(window=7).mean()
weather['humidity_7day_ma'] = weather['humidity'].rolling(window=7).mean()
weather['wind_speed_7day_ma'] = weather['wind_speed'].rolling(window=7).mean()
print("Weather Data with Moving Averages:")
print(weather[['date', 'temperature', 'temperature_7day_ma','humidity','humidity_7day_ma','wind_speed','wind_speed_7day_ma']])
#Remember these are new columns in our dataset

Weather Data with Moving Averages:
          date  temperature  temperature_7day_ma  humidity  humidity_7day_ma  \
0   2024-03-13         10.8                  NaN        60               NaN
1   2024-03-13         10.4                  NaN        62               NaN
2   2024-03-13         10.0                  NaN        63               NaN
3   2024-03-13          9.7                  NaN        63               NaN
4   2024-03-13          9.4                  NaN        64               NaN
..         ...          ...                  ...       ...               ...
163 2024-03-19          7.0             7.028571        38         31.142857
164 2024-03-19          6.9             7.114286        41         33.142857
165 2024-03-19          6.7             7.100000        43         35.428571
166 2024-03-19          6.5             7.000000        46         38.000000
167 2024-03-19          6.5             6.871429        47         40.428571

     wind_speed  wind_speed_7day_ma
0           4.0                 NaN
1           2.2                 NaN
2           2.2                 NaN
3           4.0                 NaN
4           4.0                 NaN
..          ...                 ...
163        20.2           24.228571
164        18.0           23.557143
165        18.4           22.585714
166        22.3           22.228571
167        12.6           20.428571

[168 rows x 7 columns]

In [ ]:
#There are no such null values in our dataset.And which are showing are 'Moving Averages'
weather.apply(pd.isnull).sum()

Date                   0
Time                   0
temperature            0
humidity               0
wind_speed             0
precipitation          0
date                   0
time                   0
temperature_7day_ma    6
humidity_7day_ma       6
wind_speed_7day_ma     6
dtype: int64